# Generated by Django 4.2.29 on 2026-03-15 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('badge_letter', models.CharField(max_length=5)),
                ('badge_css_class', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('period', models.CharField(blank=True, max_length=100)),
                ('is_current', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Career Entry',
                'verbose_name_plural': 'Career Entries',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('year_range', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('extra_info', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('traditional', 'Traditional / Ethnic'), ('candid', 'Candid / Travel'), ('family', 'Family'), ('casual', 'Casual / Hobby'), ('other', 'Other')], default='other', max_length=20)),
                ('object_position', models.CharField(blank=True, default='center center', max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeritageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gotra_hindi', models.CharField(max_length=100)),
                ('gotra_english', models.CharField(max_length=100)),
                ('closing_note', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Heritage Info',
                'verbose_name_plural': 'Heritage Info',
            },
        ),
        migrations.CreateModel(
            name='LineageNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hindi', models.CharField(blank=True, max_length=200)),
                ('name_english', models.CharField(blank=True, max_length=200)),
                ('role_label', models.CharField(max_length=100)),
                ('is_self', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MoolCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_hindi', models.CharField(max_length=100)),
                ('text_hindi', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('anchor', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('sanskrit_greeting', models.CharField(max_length=200)),
                ('hero_photo', models.ImageField(blank=True, upload_to='profile/')),
                ('role_title', models.CharField(max_length=100)),
                ('current_company', models.CharField(max_length=100)),
                ('company_color', models.CharField(default='#2684FF', max_length=7)),
                ('location_primary', models.CharField(max_length=100)),
                ('location_roots', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('complexion', models.CharField(max_length=50)),
                ('current_address', models.TextField(blank=True)),
                ('native_village', models.CharField(max_length=100)),
                ('native_district', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('footer_sanskrit', models.CharField(max_length=200)),
                ('copyright_year', models.PositiveIntegerField(default=2026)),
            ],
            options={
                'verbose_name': 'Personal Info',
                'verbose_name_plural': 'Personal Info',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMemberTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('is_amber', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='biodata.familymember')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
