# Generated by Django 4.2.29 on 2026-03-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0002_seed_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
